spring:
  main:
    banner-mode: console
  datasource:
#    url: jdbc:postgresql://postgres:5432/test
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: "create-drop"
